# Generated by Django 3.1.1 on 2020-09-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('businessEmail', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('businessName', models.CharField(max_length=30)),
                ('businessAddress', models.CharField(max_length=30)),
                ('legalNumber', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('businessType', models.CharField(max_length=30)),
                ('accountStatus', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('communityNumber', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='communityNumber')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
                ('regin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentInfo',
            fields=[
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('phone', models.IntegerField()),
                ('accountStatus', models.BooleanField(default=False)),
                ('comunityNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.community')),
            ],
        ),
        migrations.CreateModel(
            name='Resident_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.categories')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.residentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ComunityCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.categories')),
                ('comunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.community')),
            ],
        ),
        migrations.CreateModel(
            name='Bussiness_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.businessinfo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.categories')),
            ],
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='comunityNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.community'),
        ),
    ]
