# Generated by Django 3.1.1 on 2020-09-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='legalNumber',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
