# Generated by Django 3.1.1 on 2020-09-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200925_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessinfo',
            name='legalNumber',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
