# Generated by Django 3.1.1 on 2020-09-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200925_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness_categories',
            name='category',
        ),
        migrations.AddField(
            model_name='bussiness_categories',
            name='category',
            field=models.ManyToManyField(to='API.Categories'),
        ),
        migrations.RemoveField(
            model_name='comunitycategories',
            name='category',
        ),
        migrations.AddField(
            model_name='comunitycategories',
            name='category',
            field=models.ManyToManyField(to='API.Categories'),
        ),
        migrations.RemoveField(
            model_name='resident_categories',
            name='category',
        ),
        migrations.AddField(
            model_name='resident_categories',
            name='category',
            field=models.ManyToManyField(to='API.Categories'),
        ),
    ]
